version: '3'

services:
  mysql:
    image: mysql:8.0.18
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./init.sql:/data/application/init.sql
          - ./mysql:/var/lib/mysql
    command: --init-file /data/application/init.sql
  wildfly:
    build: .
    ports:
      - 4390:8080
      - 4391:9990