version: '3'

services:
  mysql:
    image: mysql:8.0.18
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:3306
#    volumes:
#      - ./mysql:/var/lib/mysql
#  wildfly:
#    build: .
#    ports:
#      - 8080:8080
#      - 9990:9990